version: '3.8'
name: unidatex-development

services:
  postgres:
    image: 'postgres:17-alpine'

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - ${POSTGRES_PORT}:5432

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  redis:
    image: 'redis:7.4-alpine'
    command: ['redis-server', '--requirepass', '$REDIS_PASSWORD']
    ports:
      - ${REDIS_PORT}:6379
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}

  smtp-server:
    image: 'datydock/mailslurper'

    ports:
      - 8080:8080
      - 8085:8085
      - 2500:2500
