version: '3.9'

services:
  seaweed_master:
    image: chrislusf/seaweedfs
    container_name: seaweed_master
    ports:
      - 9333:9333
    command: 'master -ip=seaweed_master -volumeSizeLimitMB=1024'

  seaweed_volume:
    image: chrislusf/seaweedfs
    container_name: seaweed_volume
    ports:
      - 8080:8080
    command: 'volume -ip=seaweed_volume -mserver=seaweed_master:9333 -port=8080 -preStopSeconds=1'
    depends_on:
      - seaweed_master

  s3:
    image: chrislusf/seaweedfs
    ports:
      - 8000:8000
    command: 'filer -master="seaweed_master:9333" -s3 -s3.config=/etc/seaweedfs/s3.json -s3.port=8000 -s3.allowEmptyFolder=false -s3.allowDeleteBucketNotEmpty=false'
    volumes:
      - ./s3.json:/etc/seaweedfs/s3.json
    depends_on:
      - seaweed_master
      - seaweed_volume
