version: '3.9'
name: unidatex-development

include:
  - docker-compose.s3.dev.yaml

services:
  postgres:
    image: 'postgres:17-alpine'

    environment:
      POSTGRES_USER: ${UNDX_POSTGRES_USER}
      POSTGRES_PASSWORD: ${UNDX_POSTGRES_PASSWORD}
      POSTGRES_DB: ${UNDX_POSTGRES_DB}

    ports:
      - ${UNDX_POSTGRES_PORT}:5432

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  redis:
    image: 'redis:7.4-alpine'
    command: ['redis-server', '--requirepass', '$UNDX_REDIS_PASSWORD']
    ports:
      - ${UNDX_REDIS_PORT}:6379
    environment:
      REDIS_PASSWORD: ${UNDX_REDIS_PASSWORD}
      REDIS_PORT: ${UNDX_REDIS_PORT}

  smtp-server:
    image: 'maildev/maildev'

    ports:
      - 1080:1080
      - 1025:1025
